FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY scripts/webhook.py ./scripts/webhook.py
COPY scripts/pipeline.py ./scripts/pipeline.py

CMD ["uvicorn", "scripts.webhook:app", "--host", "0.0.0.0", "--port", "8000"]
